### ISSUE TITLE
Relax click requirement to support new Docker stack

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-dev#26]
@unkcpz @yakutovicha is this package still supported and a good way to develop `aiidalab` and `aiidalab-home`?

I just tried to install it via pip in the new docker stack and it downgraded the click version from version `8.1.3` to `7.1.3`. 
I've reverted the downgraded and it seems to work with version 8 just fine so just relaxing the requirement should fix this I think.

(NOTE: The README should be updated to make the purpose of this package clearer. Also there seem to be some strayed files, `setup.json` and `requirements.txt` that should be deleted since there is the `setup.cfg` file.

**Comment by unkcpz** [comment]
I don't know about this repo and never use it. It seems a useful tool but I think I am reluctant to bringing up more things to our development tool stack.

**Comment by danielhollas** [comment]
@unkcpz I've been playing with this and I found it super useful. In the UI it even displays that `AiiDAlab` is in development mode, and you can easily switch between development and production. I opened a quick PR for thi.

**Comment by unkcpz** [comment]
Interesting didn't realize it supports UI as well. Please fix this and I'll give it a try.

**Comment by danielhollas** [comment]
@unkcpz would you mind adding this to the current sprint of AiiDAlab Roadmap. Just to make it visible to the others that this was done (and that this package exists :D )
